version: '3.8'

services:
  web:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/
    environment:
      DB_HOST: "${DB_HOST}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./src:/var/www
    networks:
      - laravel
  mysql:
    image: mysql:8.1
    networks:
      - laravel
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
  # postgres:
  #   image: postgres:15-alpine
  #   volumes:
  #     - "./data/db/psql:/var/lib/postgresql/data"
  #   environment:
  #     - POSTGRES_USER="${DB_USERNAME}"
  #     - POSTGRES_PASSWORD="${DB_PASSWORD}"
  #     - POSTGRES_DB="${DB_DATABASE}"
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - laravel
  # redis:
  #   image: redis:7.2
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - laravel
  #   volumes:
  #     - "./data/redis:/data"
networks:
  laravel:
    driver: bridge
volumes:
  cache: { }

